### ISSUE TITLE
UnicodeDecodeError:  -> crash

### ISSUE THREAD

**Issue by Faberle** [rodricios/eatiht#13]
I get the following killer error while trying to extract articles from this german website: 

````
Traceback (most recent call last):
  File "extract.py", line 6, in <module>
    tree = etv2.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/eatiht/etv2.py", line 214, in ext                                        ract
    subtrees = get_textnode_subtrees(html_tree)
  File "/usr/local/lib/python2.7/dist-packages/eatiht/etv2.py", line 198, in get                                        _textnode_subtrees
    for n in nodes_with_text]
  File "lxml.etree.pyx", line 1498, in lxml.etree._Element.xpath (src/lxml/lxml.                                        etree.c:52102)
  File "xpath.pxi", line 307, in lxml.etree.XPathElementEvaluator.__call__ (src/                                        lxml/lxml.etree.c:151941)
  File "xpath.pxi", line 230, in lxml.etree._XPathEvaluatorBase._handle_result (                                        src/lxml/lxml.etree.c:150939)
  File "extensions.pxi", line 621, in lxml.etree._unwrapXPathObject (src/lxml/lx                                        ml.etree.c:145771)
  File "extensions.pxi", line 655, in lxml.etree._createNodeSetResult (src/lxml/                                        lxml.etree.c:146126)
  File "extensions.pxi", line 676, in lxml.etree._unpackNodeSetEntry (src/lxml/l                                        xml.etree.c:146323)
  File "extensions.pxi", line 786, in lxml.etree._buildElementStringResult (src/                                        lxml/lxml.etree.c:147530)
  File "apihelpers.pxi", line 1371, in lxml.etree.funicode (src/lxml/lxml.etree.                                        c:26844)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 24: invalid                                         start byte
````
Help would be appreciated

Christian

**Comment by jjangsangy** [comment]
Just saw this issue out of the blue and thought I might put in some info.

Most likely the issue is coming from this line
https://github.com/rodricios/eatiht/blob/master/eatiht/v2.py#L117

The assumption is that the website is going to be encoded in utf-8, which is true most of the time, but not always.

Reference [here](https://wiki.python.org/moin/UnicodeDecodeError) for more details on the issue. 

> A `UnicodeDecodeError` may happen when encoding. The cause of it seems to be the coding-specific `encode()` functions that normally expect a parameter of type unicode. 

It's kind of an inevitability when dealing with many websites and many different contexts, most of the time utf-8 is pretty safe, but otherwise figuring out the websites encoding scheme is difficult. Also the way that Python handled unicode using the `unicode()` constructor isn't very good practice as Python 3 has deprecated unicode and promoting the `str` type as unicode, which is IMO the right thing to do.

For more information on this issue as well as encoding practices in general, here are some good references.

* http://lucumr.pocoo.org/2014/5/12/everything-about-unicode/
* http://agiliq.com/blog/2014/12/understanding-python-unicode-str-unicodeencodeerro/

**Comment by rodricios** [comment]
Hi @jjangsangy! Thanks for taking the time to look into these issues. I'll try to find time to read the material you've referenced. About the Python2/3 unicode/str collision, it's a problem that I hope can be nipped in the bud soon enough. Pull requests wanted :)

**Comment by jjangsangy** [comment]
Already fixed it!

**Comment by rodricios** [comment]
Yay! Thanks I really appreciate it!
